### ISSUE TITLE
Add compatibility for the FIPS enabled systems

### ISSUE THREAD

**Issue by ashiqueps** [WinRb/rubyntlm#44]
## Description
The MD5 algorithm is not FIPS compliant. When running the `winrm` from an FIPS enabled system, due to the use of MD5 algorithm, it raises the following exception. 
```ruby
Digest initialization failed: disabled for fips
```

Currently the MD5 algorithm is used in several places throughout the codebase.
https://github.com/WinRb/rubyntlm/search?q=MD5

## Backtrace
```ruby
/opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `initialize'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:35:in `block (3 levels) in <class:Digest>'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `new'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/openssl/digest.rb:41:in `block (3 levels) in <class:Digest>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:149:in `ntlm_hash'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm.rb:162:in `ntlmv2_hash'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:192:in `ntlmv2_hash'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:196:in `calculate_user_session_key!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client/session.rb:27:in `authenticate!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/rubyntlm-0.6.3/lib/net/ntlm/client.rb:36:in `init_context'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:244:in `init_auth'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:168:in `send_request'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:153:in `max_envelope_size_kb'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:78:in `max_fragment_blob_size'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:203:in `fragmenter'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:167:in `block in open_shell_payload'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `map'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `open_shell_payload'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:123:in `open_shell'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:170:in `block in open'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/retryable.rb:35:in `retryable'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:168:in `open'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:128:in `with_command_shell'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:79:in `run'
```

## Environment
```bash
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
# sysctl crypto.fips_enabled
crypto.fips_enabled = 1
```

## Expected Result

Use any of the FIPS compliant algorithms so that we can use winrm from FIPS enabled systems. 

## Additional context
This issue was discovered while trying to debug the below issue.
https://github.com/chef/chef-workstation/issues/2111

**Comment by ashiqueps** [comment]
The NTLM protocol requires MD4, MD5 algorithms for solving the server challenge and create the client challenge in order to prove the knowledge of the user password. We cannot replace these algorithms with FIPS compliant algorithms since the client challenge created will be different and will no longer able to authenticate with server.
